import { Platform, StyleSheet } from "react-native";

export const S = StyleSheet.create({

  // ── Root & Loading ─────────────────────────────────────────────────────────
  root: { flex: 1, backgroundColor: "#0f172a" },
  loadingScreen: {
    flex: 1,
    backgroundColor: "#0f172a",
    justifyContent: "center",
    alignItems: "center",
    gap: 14,
  },
  loadingText: {
    color: "#64748b",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 0.8,
  },

  // ── Floating Header ────────────────────────────────────────────────────────
  floatingHeader: {
    position: "absolute",
    top: Platform.OS === "ios" ? 60 : 40,
    left: 20,
    right: 20,
    zIndex: 20,
  },
  headerCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 14,
    borderRadius: 20,
    elevation: 12,
    shadowColor: "#1e1b4b",
    shadowOpacity: 0.45,
    shadowRadius: 24,
  },
  livePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(16,185,129,0.12)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(16,185,129,0.2)",
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#10b981",
  },
  liveText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#10b981",
    letterSpacing: 1.5,
  },
  filterBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  filterBtnActive: {
    backgroundColor: "#4f46e5",
    borderColor: "#4338ca",
  },
  filterBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#a5b4fc",
  },
  filterBtnTextActive: {
    color: "#fff",
  },

  // ── Collapsible Filter Panel ───────────────────────────────────────────────
  filterPanel: {
    position: "absolute",
    top: Platform.OS === "ios" ? 138 : 118,
    left: 20,
    right: 20,
    zIndex: 19,
    backgroundColor: "#0d1525",
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: "#1e2d45",
    shadowColor: "#000",
    shadowOpacity: 0.6,
    shadowRadius: 30,
    elevation: 16,
  },
  filterPanelLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: "#475569",
    letterSpacing: 2,
    marginBottom: 10,
    marginTop: 14,
  },
  filterScrollRow: {
    gap: 8,
    paddingBottom: 2,
  },
  filterRowWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#1a2540",
    borderWidth: 1,
    borderColor: "#243352",
  },
  chipText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#64748b",
  },
  chipTextActive: {
    color: "#fff",
  },
  typeChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#1a2540",
    borderWidth: 1,
    borderColor: "#243352",
  },
  typeChipActive: {
    backgroundColor: "#4f46e5",
    borderColor: "#4338ca",
  },
  typeChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#64748b",
  },
  typeChipTextActive: {
    color: "#fff",
  },
  budgetChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#1a2540",
    borderWidth: 1,
    borderColor: "#243352",
  },
  budgetChipActive: {
    backgroundColor: "#10b981",
    borderColor: "#059669",
  },
  budgetChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#64748b",
  },
  budgetChipTextActive: {
    color: "#fff",
  },

  // ── Map Pins ───────────────────────────────────────────────────────────────
  pin: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 100,
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
    shadowColor: "#000",
    shadowOpacity: 0.55,
    shadowRadius: 10,
    elevation: 6,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.85)",
  },
  pinDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  pinLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: 0.3,
  },
  bidCheckDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#fff",
    opacity: 0.9,
  },

  // ── Floating Stats Card ────────────────────────────────────────────────────
  statsCard: {
    position: "absolute",
    bottom: 40,
    left: 20,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0d1525",
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "#1e2d45",
    shadowColor: "#000",
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 10,
  },
  statItem: {
    alignItems: "center",
    minWidth: 48,
  },
  statValue: {
    fontSize: 17,
    fontWeight: "800",
    color: "#f1f5f9",
    letterSpacing: -0.3,
  },
  statLabel: {
    fontSize: 9,
    fontWeight: "700",
    color: "#475569",
    marginTop: 3,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  statDivider: {
    width: 1,
    height: 28,
    backgroundColor: "#1e2d45",
    marginHorizontal: 14,
  },

  // ── Squad Pill ─────────────────────────────────────────────────────────────
  squadPill: {
    position: "absolute",
    bottom: 40,
    right: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: "#4f46e5",
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: 18,
    shadowColor: "#4f46e5",
    shadowOpacity: 0.45,
    shadowRadius: 16,
    elevation: 10,
  },
  squadPillText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: 0.2,
  },

  // ── Squad List Panel ───────────────────────────────────────────────────────
  squadPanel: {
    position: "absolute",
    bottom: 104,
    left: 20,
    right: 20,
    backgroundColor: "#0d1525",
    borderRadius: 20,
    paddingTop: 18,
    paddingBottom: 22,
    borderWidth: 1,
    borderColor: "#1e2d45",
    shadowColor: "#000",
    shadowOpacity: 0.55,
    shadowRadius: 30,
    elevation: 14,
  },
  squadPanelHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 14,
  },
  squadPanelTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#e2e8f0",
    letterSpacing: -0.2,
  },
  squadCloseBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: "#1a2540",
    justifyContent: "center",
    alignItems: "center",
  },
  squadCard: {
    width: 210,
    backgroundColor: "#1a2540",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#243352",
  },
  squadCardJoined: {
    borderColor: "#10b981",
    backgroundColor: "rgba(16,185,129,0.04)",
  },
  squadCardIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(99,102,241,0.12)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  squadCardTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#f1f5f9",
    marginBottom: 3,
  },
  squadCardLead: {
    fontSize: 11,
    color: "#64748b",
    marginBottom: 12,
    fontWeight: "500",
  },
  squadCardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  squadMembersPill: {
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: "#243352",
  },
  squadMembersText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#818cf8",
  },
  squadPayout: {
    fontSize: 14,
    fontWeight: "800",
    color: "#10b981",
  },

  // ── Bottom Sheet ───────────────────────────────────────────────────────────
  sheetContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: "#0d1525",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    paddingBottom: Platform.OS === "ios" ? 42 : 28,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: "#1e2d45",
    shadowColor: "#000",
    shadowOpacity: 0.65,
    shadowRadius: 40,
    elevation: 28,
  },
  sheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#243352",
    alignSelf: "center",
    marginBottom: 22,
  },
  sheetCloseBtn: {
    position: "absolute",
    top: 22,
    right: 22,
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#1a2540",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#243352",
  },

  // Sheet — Job detail
  sheetTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 14,
  },
  sheetAccent: {
    width: 3,
    borderRadius: 2,
    alignSelf: "stretch",
    marginTop: 3,
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#f1f5f9",
    letterSpacing: -0.4,
    lineHeight: 24,
  },
  sheetMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 5,
  },
  sheetMetaText: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "500",
  },
  sheetBudget: {
    fontSize: 22,
    fontWeight: "800",
    color: "#10b981",
    letterSpacing: -0.8,
  },
  scheduledBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: "rgba(99,102,241,0.1)",
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
    alignSelf: "flex-start",
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.2)",
  },
  scheduledText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#818cf8",
  },
  alreadyBidBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(16,185,129,0.08)",
    padding: 12,
    borderRadius: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(16,185,129,0.2)",
  },
  alreadyBidText: {
    fontSize: 12,
    color: "#10b981",
    fontWeight: "700",
  },
  bidSectionLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: "#475569",
    letterSpacing: 2,
    marginBottom: 10,
  },
  bidRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  bidInputWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1a2540",
    borderRadius: 16,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: "#243352",
  },
  bidCurrency: {
    fontSize: 18,
    fontWeight: "800",
    color: "#475569",
    marginRight: 6,
  },
  bidInput: {
    flex: 1,
    fontSize: 22,
    fontWeight: "800",
    color: "#f1f5f9",
    paddingVertical: 16,
    letterSpacing: -0.5,
  },
  bidSubmitBtn: {
    paddingHorizontal: 22,
    paddingVertical: 18,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    minWidth: 96,
  },
  bidSubmitBtnDisabled: {
    opacity: 0.4,
  },
  bidSubmitText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#fff",
  },

  // Sheet — Squad
  squadSheetHero: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderRadius: 20,
    padding: 18,
    marginBottom: 16,
  },
  squadSheetIcon: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.08)",
    justifyContent: "center",
    alignItems: "center",
  },
  squadSheetTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: -0.3,
  },
  squadSheetLead: {
    fontSize: 12,
    color: "rgba(255,255,255,0.55)",
    marginTop: 3,
    fontWeight: "500",
  },
  squadSheetStats: {
    flexDirection: "row",
    backgroundColor: "#1a2540",
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#243352",
  },
  squadSheetStat: {
    flex: 1,
    alignItems: "center",
  },
  squadSheetStatVal: {
    fontSize: 22,
    fontWeight: "800",
    color: "#f1f5f9",
    letterSpacing: -0.5,
  },
  squadSheetStatLabel: {
    fontSize: 9,
    fontWeight: "700",
    color: "#475569",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginTop: 5,
  },
  sheetStatDivider: {
    width: 1,
    backgroundColor: "#243352",
    marginHorizontal: 12,
  },
  joinSquadBtn: {
    backgroundColor: "#4f46e5",
    borderRadius: 16,
    height: 56,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  joinSquadBtnJoined: {
    backgroundColor: "#1e2d45",
    borderWidth: 1,
    borderColor: "#243352",
  },
  joinSquadBtnText: {
    fontSize: 15,
    fontWeight: "800",
    color: "#fff",
  },

  // ── Web List Surface (replaces map on web) ──────────────────────────────────
  webListSurface: {
    flex: 1,
    backgroundColor: "#0f172a",
  },
  webListContent: {
    paddingTop: Platform.OS === "ios" ? 210 : 190,
    paddingHorizontal: 20,
    paddingBottom: 40,
    gap: 10,
  },
  webListEmpty: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 80,
    gap: 12,
  },
  webListEmptyText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#475569",
  },
  webListCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#0d1525",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#1e2d45",
  },
  webListAccent: {
    width: 4,
    height: 38,
    borderRadius: 2,
  },
  webListCardTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#f1f5f9",
    marginBottom: 4,
  },
  webListMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  webListMetaText: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "500",
  },
  webListBudget: {
    fontSize: 16,
    fontWeight: "800",
    color: "#10b981",
    letterSpacing: -0.4,
  },
  webListBidTag: {
    fontSize: 9,
    fontWeight: "700",
    color: "#10b981",
    marginTop: 3,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
});